---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Kamen, škare i papir
description: U ovom projektu napravit ćeš igru Kamen, škare i papir i igrati ju protiv računala.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Kamen, škare i papir
  - 
    title: "Igrač je prvi na redu"
  - 
    title: "Računalo je na redu"
  - 
    title: Provjeri rezultat
  - 
    title: 'Izazov: ASCII umjetnost'
  - 
    title: 'Izazov: Napravi novu igru'
