---
hero_image: Kuvien / kivi-paperi-scissors.png
theme: punainen
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, ohjelmointi-1, phys-comp-0, valmistus-0, yhteisö-0
title: Kivi paperi sakset
description: Create your own 'Rock, Paper, Scissors' game.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: pelit
technologies: pytonkäärme
site_areas: hankkeet
hardware: ''
software: pytonkäärme
version: 3
last_tested: 01.1.2017
steps:
  - 
    title: esittely
  - 
    title: "Pelaajan käännös"
  - 
    title: "Tietokoneen kääntyminen"
  - 
    title: Tarkista tulos
  - 
    title: 'Haaste: ASCII Art'
  - 
    title: 'Haaste: Luo uusi peli'
