---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Piedra, papel o tijera
description: Crea tu propio juego 'Piedra, papel o tijera'.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
  completion: engaged
- title: Turno del jugador
- title: Turno del ordenador
- title: Comprueba el resultado
- title: 'Reto: Arte ASCII'
  completion: internal
- title: 'Reto: Crea un nuevo juego'
