---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Carreg, Papur, Sisiwrn
description: Creu gêm 'Carreg, Papur, Sisiwrn'.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Cyflwyniad
  completion: engaged
- title: Tro'r Chwareuwr
- title: Tro'r Cyfrifiadur
- title: Gwirio'r Canlyniad
- title: 'Her: Celf ASCII'
  completion: internal
- title: 'Her: Creu gêm newydd'
