---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Schere, Stein, Papier
description: Erstelle dein eigenes „Schere, Stein, Papier“ Spiel.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: Spiele
technologies: Python
site_areas: codeclub, python
hardware: ''
software: Python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: "Der Spieler ist dran"
  - 
    title: "Der Computer ist dran"
  - 
    title: Das Ergebnis prüfen
  - 
    title: 'Aufgabe: ASCII Bilder'
  - 
    title: 'Aufgabe: Ein neues Spiel erstellen'
