---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Schere, Stein, Papier
description: Create your own 'Rock, Paper, Scissors' game.
original_url: https://codeclubprojects.org/de-DE/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Der Spieler ist dran
  - 
    title: Der Computer ist dran
    completion:
      - engaged
  - 
    title: Das Ergebnis prüfen
    completion:
      - internal
  - 
    title: 'Aufgabe: ASCII Bilder'
  - 
    title: 'Aufgabe: Ein neues Spiel erstellen'
