---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Pedra, Papel e Tesoura
description: Crie o seu próprio jogo 'Pedra, Papel e Tesoura'.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introdução
- title: Turno do Jogador
- title: Turno do Computador
  completion:
  - engaged
- title: Verifique o resultado
  completion:
  - internal
- title: 'Desafio: Arte ASCII'
- title: 'Desafio: Crie um jogo novo'
