---
hero_image: images/rock-paper-scissors.png
theme: rojo
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Piedra, Papel o Tijeras
description: Crea tu propio juego de "Piedra, Papel o Tijeras".
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: juegos
technologies: Python
site_areas: proyectos
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: "Turno del jugador"
  - 
    title: "Turno de la computadora"
  - 
    title: Verifica el resultado
  - 
    title: 'Desafío: Arte ASCII'
  - 
    title: 'Desafío: Crea un nuevo juego'
