---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Papier, Kamień, Nożyce
description: Stwórz własną grę "Papier, Kamień, Nożyce".
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Wprowadzenie
  completion: engaged
- title: Ruch gracza
- title: Ruch komputera
- title: Sprawdzanie wyniku
- title: 'Wyzwanie: ASCII Art'
  completion: internal
- title: 'Wyzwanie: stwórz nową grę'
