---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Papir, kamen, makaze
description: Napravi svoju igru 'Papir, kamen, makaze'.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: "Igrač je na redu"
  - 
    title: "Računar je na redu"
  - 
    title: Provjeri rezultat
  - 
    title: 'Izazov: ASCII umjetnost'
  - 
    title: 'Izazov: Napravi novu igru'
