---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Chifoumi - Pierre-feuille-ciseaux
description: Créer ton propre jeu 'Pierre-feuille-ciseaux'.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Le tour du joueur
- title: Le tour de l'ordinateur
  completion:
  - engaged
- title: Vérifier le résultat
  completion:
  - internal
- title: 'Défi: L''art ASCII'
- title: 'Défi: Créer un nouveau jeu'
