---
hero_image: images/rock-paper-scissors.png
theme: rouge
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Chifoumi - Pierre-feuille-ciseaux
description: Créer ton propre jeu 'Pierre-feuille-ciseaux'.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: codeclub, python
hardware: ''
software: python
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Introduction
  - 
    title: "Le tour du jouer"
  - 
    title: "Le tour de l'ordinateur"
  - 
    title: Vérifier le résultat
  - 
    title: 'Défi : L''art ASCII'
  - 
    title: 'Défi : Créer un nouveau jeu'
