---
hero_image: images/rock-paper-scissors.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-0, programlama-1, fiziksel-hesaplama-0, üretim-0, topluluk-0
title: Taş - Kağıt - Makas
description: Kendi 'Taş, Kağıt, Makas' oyununuzu yaratın.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Giriş
- title: Oyuncunun Sırası
- title: Bilgisayarın Sırası
  completion:
  - engaged
- title: Sonucu Kontrol Et
  completion:
  - internal
- title: 'Meydan Okuma: ASCII Sanatı'
- title: 'Meydan Okuma: Yeni bir oyun yaratın'
